name: xOS Build Desktop
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "31 6 * * 0" # 6:31 UTC Sunday
    - cron: "31 6 * * 1,2,3,4,5,6" # 6:31 UTC Monday-Saturday
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-desktop-stable:
    name: Desktop Stable
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      images: '["bluefin", "bluefin-dx"]'
      streams: '["stable"]'
      flavors: '["main", "nvidia"]'
#  build-desktop-testing:
#    name: Desktop Beta(Testing)
#    uses: ./.github/workflows/reusable-build.yml
#    secrets: inherit
#    with:
#      images: '["bluefin", "bluefin-dx"]'
#      streams: '["beta"]'
#      flavors: '["main", "nvidia"]'
